MODEL:
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: './logs/stage1/swin_transformer/swin_transformer_40.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  Transformer_TYPE: 'swin_base_patch4_window7_224'
  STRIDE_SIZE: [12, 12]

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('aic')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 3
  BASE_LR: 0.0004
  IMS_PER_BATCH: 16
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: True
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 3
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  FP16_ENABLED: True

TEST:
  IMS_PER_BATCH: 16
  RE_RANKING: True
  RE_RANKING_TRACK: True
  WEIGHT: './logs/stage2/swin/v1/swin_transformer_2.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'no'
  EVAL: True
  FIC: True
  CROP_TEST: True
  LA: 0.11

STAGE2:
  EPS: 0.55
  LA: 0.0005
      
OUTPUT_DIR: './logs/stage2/swin_transformer/v1'
