MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './pretrained/swin_base_patch4_window12_384_22kto1k.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'swin_transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  Transformer_TYPE: 'swin_base_patch4_window12_384_22kto1k'
  STRIDE_SIZE: [12, 12]
  SWIN_TRANSFORMER_WINDOW_SIZE: 12

INPUT:
  SIZE_TRAIN: [384, 384]
  SIZE_TEST: [384, 384]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('aic_sim')
  PLUS_NUM_ID: 100

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 40
  BASE_LR: 0.01
  IMS_PER_BATCH: 16
  STEPS: [20, 35]
  GAMMA: 0.
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 5
  WARMUP_METHOD: 'cosine'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 4
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  FP16_ENABLED: True

TEST:
  IMS_PER_BATCH: 16
  RE_RANKING: False
  RE_RANKING_TRACK: True
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
  EVAL: True
  FIC: True
OUTPUT_DIR: './logs/stage1/swin_transformer'
